<?php

defined('WORKER_FOR_HOURS_AND_TOOLS') or define('WORKER_FOR_HOURS_AND_TOOLS', 'worker_for_hours_and_tools');
defined('WORKER_FOR_HOURS') or define('WORKER_FOR_HOURS', 'worker_for_hours');
defined('WORKER_FOR_TOOLS') or define('WORKER_FOR_TOOLS', 'worker_for_tools');
defined('FREE_TRIAL_DAYS') or define('FREE_TRIAL_DAYS', 30);
defined('TRIAL_END_ALERT_AFTER_DAYS') or define('TRIAL_END_ALERT_AFTER_DAYS', 7);
defined('TRIAL_END_MSG_AFTER_DAYS') or define('TRIAL_END_MSG_AFTER_DAYS', 14);
defined('TRIAL_END_NOTIFICATION_BEFORE_DAYS') or define('TRIAL_END_NOTIFICATION_BEFORE_DAYS', 3);
defined('TRIAL_END_NOTIFICATION_AFTER_DAYS_FIRST') or define('TRIAL_END_NOTIFICATION_AFTER_DAYS_FIRST', 7);
defined('TRIAL_END_NOTIFICATION_AFTER_DAYS_SECOND') or define('TRIAL_END_NOTIFICATION_AFTER_DAYS_SECOND', 14);
defined('SMS_TEXT_MAX_LENGTH') or define('SMS_TEXT_MAX_LENGTH', 500);
defined('DEFAULT_SERVER_TIMEZONE') or define('DEFAULT_SERVER_TIMEZONE', 'UTC');
defined('DEFAULT_USER_TIMEZONE') or define('DEFAULT_USER_TIMEZONE', 'Europe/Berlin');// CEST
defined('SUPPORT_PHONE_NUMBER') or define('SUPPORT_PHONE_NUMBER', '+45 52 73 11 83');
defined('SUPPORT_EMAIL_ADDRESS') or define('SUPPORT_EMAIL_ADDRESS', 'info@worker.nu');

return [
    'WORKER_FOR_HOURS_AND_TOOLS' => WORKER_FOR_HOURS_AND_TOOLS,
    'WORKER_FOR_HOURS' => WORKER_FOR_HOURS,
    'WORKER_FOR_TOOLS' => WORKER_FOR_TOOLS,
    'FREE_TRIAL_DAYS' => FREE_TRIAL_DAYS,
    'TRIAL_END_ALERT_AFTER_DAYS' => TRIAL_END_ALERT_AFTER_DAYS,
    'TRIAL_END_MSG_AFTER_DAYS' => TRIAL_END_MSG_AFTER_DAYS,
    'TRIAL_END_NOTIFICATION_BEFORE_DAYS' => TRIAL_END_NOTIFICATION_BEFORE_DAYS,
    'TRIAL_END_NOTIFICATION_AFTER_DAYS_FIRST' => TRIAL_END_NOTIFICATION_AFTER_DAYS_FIRST,
    'TRIAL_END_NOTIFICATION_AFTER_DAYS_SECOND' => TRIAL_END_NOTIFICATION_AFTER_DAYS_SECOND,
    'SMS_TEXT_MAX_LENGTH' => SMS_TEXT_MAX_LENGTH,
    'DEFAULT_SERVER_TIMEZONE' => DEFAULT_SERVER_TIMEZONE,
    'DEFAULT_USER_TIMEZONE' => DEFAULT_USER_TIMEZONE,
    'SUPPORT_PHONE_NUMBER' => SUPPORT_PHONE_NUMBER,
    'SUPPORT_EMAIL_ADDRESS' => SUPPORT_EMAIL_ADDRESS,
];

?>